
[greenclip]
  max_history_length = 500
  history_file = "/home/josh/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  use_primary_selection_as_input = false
  blacklisted_applications = [""]
  trim_space_from_selection = true
  enable_image_support = true
  static_history = [""]
  max_selection_size_bytes = 0
